export const docPathByModuleKey: Record<string, string> = {
  dashboard: '/docs/dashboard',
  units: '/docs/units',
  technicians: '/docs/technicians',
  receiving: '/docs/receiving',
  receiving_history: '/docs/receiving-history',
  customers: '/docs/customers',
  sales_orders: '/docs/sales-orders',
  work_orders: '/docs/work-orders',
  inventory: '/docs/inventory',
  purchase_orders: '/docs/purchase-orders',
  invoices: '/docs/invoices',
  scheduling: '/docs/scheduling',
  parts: '/docs/parts',
  vendors: '/docs/vendors',
  settings: '/docs/settings',
  users: '/docs/users',
  admin_users: '/docs/users',
  warranty_returns: '/docs/returns-warranty',
};
